FROM php:8.1-fpm
WORKDIR /app
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip
RUN apt-get clean && rm -rf /var/lib/apt/lists/*
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd
RUN curl -sL https://deb.nodesource.com/setup_16.x | bash -
RUN apt-get install -y nodejs
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
COPY ./composer.json ./
RUN composer install --ignore-platform-reqs --no-scripts --no-autoloader
COPY . .
RUN composer dump-autoload --optimize
RUN chown -R www-data:www-data /app/storage /app/bootstrap/cache
RUN chmod -R 775 /app/storage /var/www/html/bootstrap/cache
EXPOSE 9000
CMD ["php-fpm"]
RUN npm install
RUN npm run dev

